### ISSUE TITLE
when using gnome-tweak to remap capslock key to ctrl, the program does not translate keystrokes to qwerty when capslock is pressed

### ISSUE THREAD

**Issue by pigeonman99** [tbocek/dvorak#21]
i use gnome-tweak to remap capslock to ctrl for better ergonomics. 

when i press capslock-* the program does not translate to qwerty. i.e. i had to press capslock-i to copy.

**Comment by tbocek** [comment]
I believe the gnome mapping happens after I captures the keycodes. In order to make this work, a 5th modifier (CAPS_LOCK) needs to be added here: https://github.com/tbocek/dvorak/blob/c72932ee331f33b6e818788e2cd28a3db5a88ec7/dvorak.c#L90  and here https://github.com/tbocek/dvorak/blob/c72932ee331f33b6e818788e2cd28a3db5a88ec7/dvorak.c#L439, ideally with a flag here: https://github.com/tbocek/dvorak/blob/c72932ee331f33b6e818788e2cd28a3db5a88ec7/dvorak.c#L228

**Comment by pigeonman99** [comment]
thanks for the pointer! let me try your suggestion and see how it goes. will report back.
