### ISSUE TITLE
Sometimes it does not work.

### ISSUE THREAD

**Issue by nemonein** [tbocek/dvorak#23]
Hello. I really appreciate your work. Thank you very much.
I use 'dvorak' on Archlinux with KDE Plasma.

I use US dvorak layout and Korean input method editor(such as [KIME](https://github.com/Riey/kime)) for Korean characters. To change between US Dvorak and Korean keyboard, I press Shift-Space.
Sometimes(and frequently), dvorak program does not work. For instance when I press Ctrl+C(Qwerty C), its output is Ctrl+J.

When this happens, L-Alt 3 times is the solution, but why is this happening and is there a way to avoid this?

**Comment by tbocek** [comment]
The problem is that the mapping happen all the time, regardless if dvorak is selected or not. I tried to figure out which keyboard layout is selected, but I did not find a reliable solution. So my workaround is enabling/disabling with 3 times Alt to be able to switch to other layouts. If there is an easy way to determine the keyboard layout, I'm happy to add it.

**Comment by nemonein** [comment]
Thank you for your answer.
I hope you find a solution.
